#!/usr/bin/env bash

source scripts/env.sh

d=$1

case $1 in 
    base)
        dockerfile=Dockerfile
        build_context=.
    ;;
    *)
        if [[ ! -d src/$1 ]]; then
            echo "invalid src: src/$1"
            exit 1
        fi
        dockerfile=src/$1/Dockerfile
        build_context=src/$1
    ;;
esac

tag_name="$(dir_to_tag $1)"
info "building $tag_name"
docker build -t "$tag_name" -f $dockerfile $build_context