#!/usr/bin/env bash

source scripts/env.sh

info "building base" 
scripts/build-image base
info "$(dir_to_tag base)"

info "building gcc-prereqs"
scripts/build-image gcc-prereqs
info "$(dir_to_tag gcc-prereqs)"

info "building gcc"
scripts/build-image gcc
info "$(dir_to_tag gcc)"